### ISSUE TITLE
Not able to use library

### ISSUE THREAD

**Issue by skined90** [tntkhang/keystore-secure#1]
After adding this library to gradle dependencies and after sync, when I try to use library I just see R package and nothing more. 

```KeystoreSecure.init(context);``` does not exist. Am I doing something wrong or?

**Comment by tntkhang** [comment]
Could you try with a fresh project? I checked it and it works normally like the guide in Readme. 
Could you check after Sync project do you got the library or not?

Take a look at my screenshot: 

![alt text](https://lh4.googleusercontent.com/XAgvkb3TZUiFCfWObYIGLTfHqlzlQ8cHCkt1MO7iWSJP4SckmYdmm9MD1VJ2fsiGQnxSDWWnAv2nOOdGKgFL=w1920-h938)

**Comment by skined90** [comment]
Sorry. There was some bug with gradle obviously. Now it works. Thanks.
